// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoQT7CvHbtjk4YGiviVnzD8M_jKRAyCq4',
    appId: '1:135095249356:web:bf6325ef675a0b58af1569',
    messagingSenderId: '135095249356',
    projectId: 'sapsak-ffb34',
    authDomain: 'sapsak-ffb34.firebaseapp.com',
    storageBucket: 'sapsak-ffb34.appspot.com',
    measurementId: 'G-Z2SEQE9MGJ',
    databaseURL: 'https://sapsak-ffb34-default-rtdb.europe-west1.firebasedatabase.app'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOIV3SjpntYMJu8y4artDSN2vDULsfqg4',
    appId: '1:135095249356:android:5f72e79c1c428ddcaf1569',
    messagingSenderId: '135095249356',
    projectId: 'sapsak-ffb34',
    storageBucket: 'sapsak-ffb34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoewvtVKG51wfr2lWdKXN9M1pprruBGh4',
    appId: '1:135095249356:ios:231917e646a4cab0af1569',
    messagingSenderId: '135095249356',
    projectId: 'sapsak-ffb34',
    storageBucket: 'sapsak-ffb34.appspot.com',
    iosClientId: '135095249356-t38najmtmbipc0etvo7h3dggumiic3a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sapsak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoewvtVKG51wfr2lWdKXN9M1pprruBGh4',
    appId: '1:135095249356:ios:231917e646a4cab0af1569',
    messagingSenderId: '135095249356',
    projectId: 'sapsak-ffb34',
    storageBucket: 'sapsak-ffb34.appspot.com',
    iosClientId: '135095249356-t38najmtmbipc0etvo7h3dggumiic3a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sapsak',
  );
}
